### ISSUE TITLE
IPFS Timeout and Image Loading Issues

### ISSUE THREAD

**Issue by fabianbormann** [fabianbormann/WalkInWallet#8]
To enhance the reliability and robustness of the NFT gallery, we need to implement a retry mechanism for handling IPFS timeouts. When an image fails to load due to a timeout, the system should automatically initiate a retry attempt after a brief interval. This would prevent images from being omitted due to temporary network issues.

Additionally, we should diversify the IPFS gateways used for fetching images. By checking different IPFS gateways, we can increase the chances of successfully retrieving image data even if one gateway experiences issues or timeouts.

**Comment by kiriakos** [comment]
I think https://nftcdn.io/ could also make a great option. Even though it isn't stricktly a gateway service. I'm sure smaug would be happy to provide an economical option for such an opensource project.

**Comment by fabianbormann** [comment]
@kiriakos I'm close to a good solution with the retry mechanism but it turned out that most of the images were not loaded correctly because of a difference in the ipfs link. 98% of the tokens have ipfs links with the structure ipfs://<cid> but in some cases the metadata seems to be wrong and the link becomes ipfs/<cid> or ipfs://ipfs/<cid> .. I try to handle all those special cases now. 😉 
![image](https://github.com/fabianbormann/WalkInWallet/assets/1525818/6a77850b-c725-43b5-b6e1-cc257757f7cb)

**Comment by kiriakos** [comment]
Interesting. Is the on chain metadata really actually
```
 "image": "ipfs/QmPM..."
```
?

I'm not sure I've seen this before. Does CIP25 even account for it?

**Comment by fabianbormann** [comment]
https://cexplorer.io/asset/asset1zu7ysehnjwvxwkhprymtedecgv37pdepc9xxqu/metadata#data 

Yes it's the on-chain metadata 👍 and it's not compliant with CIP25 as it should be an uri (<protocol>://) or an array.
